name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    uses: smg-real-estate/.github-ts/.github/workflows/release-lib.yml@v0.1.8
    permissions:
      contents: write
      packages: write
      pull-requests: read
    secrets: inherit